### ISSUE TITLE
خطا در نصب برنامه توی لینوکس

### ISSUE THREAD

**Issue by YousefSyd** [HarlyquinForest/our-time-is-now#1]
با سلام 
من لینوکس کوبونتو نصب کردم برنامه qv2ray رو نصب کردم. البته چزی که نصب نمیشه فقط اجرا میشه 
خود v2ray هم این  v2ray-linux-64.zip  رو دانلود کردم.
مراحل رو به همون صورت که فرموده بودین رفتم 
یک سوال در مورد فولدر asset . ما باید اون سه تا فایل دات رو توی این فولدر بریزیم و بعد این فولدر رو بزاریم توی فولدر /usr/share/v2ray درسته؟؟
من این کار رو کردم ولی اگر توی برنامه qv2ray ادرس asset رو فولدر usr/share/v2ray بزاریم  پیغام میده فولدر asset یافت نشد. و اگر ادرس رو usr/share/v2ray/asset بزارم  خطا میزنه vcore failed with exit code:2

دو سه روز قبل لینوکس مینت داشتم همین مشکل برخوردم توی این هم باز همون مشکل هست
نمیدونم کمکی میکنه یا نه سعی کردم توی ترمنال دستور  v2ray test یا v2ray run رو بزنم که خطای پایین رو داد:
V2Ray 5.1.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19 linux/amd64)
A unified platform for anti-censorship.
2022/12/01 10:51:55 Using default config:  /home/yousef/v2ray/config.json
Test failed: main/commands: failed to load config: [/home/yousef/v2ray/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to parse domain rule: geosite:category-ads > infra/conf/rule: failed to load geosite: category-ads > infra/conf/geodata/standard: list not found in geosite.dat: category-ads

**Comment by HarlyquinForest** [comment]
@YousefSyd 
سلام 
اول از همه خیلی خوشحالم که این ریپوزیتوری توجهتونو جلب کرده و ممنون بابت issue که زدید. 

بله متاسفانه من هم تست کردم v2ray-core کانفیگ رو به درستی میخونه و با ارروری مواجهه نمی‌شه. ولی داخل qv2ray به مشکل میخوره. نیاز به کمی بررسی بیشتر داره 
پیشنهادم اینه، تا وقتی که من راه‌حلی برا این پیدا می کنم از neokray به عنوان جایگزین استفاده کنید‌. 

[nekoray](https://github.com/HarlyquinForest/our-time-is-now/tree/master/v2ray)

**Comment by HarlyquinForest** [comment]
> @HarlyquinForest سلام مجدد من هم از شما تشکر میکنم بابت این زحمتی که میکشید امیدوارم که همیشه موفق باشید مشکل من حل شد. تو یک گروه توی تلگرام این موضوع رو مطرح کردم ظاهرا اون بسته v2ray که گذاشتین یک فایل به اسم v2ctl کم داره که من از یک جای دیگه کل بسته v2ray رو دانلود کردم که اون فایل رو داشت و مشکل حل شد

بسیار عالی.
اگر براتون مقدوره فایل راهنمای نصب رو ادیت بفرمایید و pull request ارسال کنید.

**Comment by YousefSyd** [comment]
> > @HarlyquinForest سلام مجدد من هم از شما تشکر میکنم بابت این زحمتی که میکشید امیدوارم که همیشه موفق باشید مشکل من حل شد. تو یک گروه توی تلگرام این موضوع رو مطرح کردم ظاهرا اون بسته v2ray که گذاشتین یک فایل به اسم v2ctl کم داره که من از یک جای دیگه کل بسته v2ray رو دانلود کردم که اون فایل رو داشت و مشکل حل شد
> 
> بسیار عالی. اگر براتون مقدوره فایل راهنمای نصب رو ادیت بفرمایید و pull request ارسال کنید.

با عرض معذرت من با گیت هاب و نحوه انجام مواردی ک فرمودین اشنایی ندارم 
تنها چیزی که باید عوض بشه استفاده از یه ورژن قدیمی تر v2ray-cor هست که من از ورژن 4.3 استفاده کردم :
https://github.com/v2fly/v2ray-core/releases/tag/v4.31.0
ظاهرا توی ورژن اخر این برنامه،  فایلv2ctl حذف شده که isssue هم گذاشته بودن براش

**Comment by HarlyquinForest** [comment]
> > > @HarlyquinForest سلام مجدد من هم از شما تشکر میکنم بابت این زحمتی که میکشید امیدوارم که همیشه موفق باشید مشکل من حل شد. تو یک گروه توی تلگرام این موضوع رو مطرح کردم ظاهرا اون بسته v2ray که گذاشتین یک فایل به اسم v2ctl کم داره که من از یک جای دیگه کل بسته v2ray رو دانلود کردم که اون فایل رو داشت و مشکل حل شد
> > 
> > بسیار عالی. اگر براتون مقدوره فایل راهنمای نصب رو ادیت بفرمایید و pull request ارسال کنید.
> 
> با عرض معذرت من با گیت هاب و نحوه انجام مواردی ک فرمودین اشنایی ندارم 
> تنها چیزی که باید عوض بشه استفاده از یه ورژن قدیمی تر v2ray-cor هست که من از ورژن 4.3 استفاده کردم :
> https://github.com/v2fly/v2ray-core/releases/tag/v4.31.0
> ظاهرا توی ورژن اخر این برنامه،  فایلv2ctl حذف شده که isssue هم گذاشته بودن براش

خیلی خب پس من تغییرات رو اعمال می کنم. ممنون از راهنمایی تون 👍

**Comment by YousefSyd** [comment]
خواهش میکنم
بازم ممنون از بابت تمام زحماتی که میکشین
