### ISSUE TITLE
ویروسی بودن برنامه

### ISSUE THREAD

**Issue by Ramin-Setoodehnia** [HarlyquinForest/our-time-is-now#2]
سلام زمانی که برنامه دانلود میشود فایل ستاپ و حتی بعد از نصب آنتی ویروس برنامتون را به عنوان ویروس شناسایی میکند

**Comment by HarlyquinForest** [comment]
@Ramin-Setoodehnia 
سلام  ممنون از توجهتون 

فایل رو تو virustotal بررسی کردم. از ۷۰ تا آنتی ویروس مطرح فقط ۲ تا به عنوان بدافزار شناساییش می کنن که به دلیل تغییر در تنظیمات شبکه هست. 
طبیعی هم هست برنامه هایی که امضای دیجیتالی درستی و حسابی ندارن ولی تنظیمات سیستمی رو تغییر می دن معمولا مشکوک هستن مخصوصا اگر پروکسی ست کنن. 
ولی با توجه به ماهیت نرم افزار که یک  ابزار رفع فیلتر و وی پی ان هست این رفتار طبیعیه. 
چون به صورت خودکار برای اینکه ترافیک کل سیستم عامل از طریق پروکسی سروری که برنامه ایجاد می کنه عبور داده بشه به صورت خودکار تتظیمات مربوط به پروکسی ویندوز رو  تغییر میده. 
اگر رو این موضوع حساسید و طبیعیه که باشید احتمالا گزینه ای وجود داره که به صورت اتوماتیک این مقادیرو ست نکنه و خودتون به صورت دستی تو مرورگر، تلگرام و یا برنامه هایی که نیاز به وی پی ان دارند استفاده کنید. برای اینکه آنتی ویروستون هم گیر نده باید مسیر اجرای برنامه رو به عنوان استثنا یا Exception یا هر اصطلاح ای، تو آنتی ویروس ست کنید که بستگی به آنتی ویرستون مراحل متفاوتی داره.
