### ISSUE TITLE
مشکل کانکتینگ با برخی اپراتورها

### ISSUE THREAD

**Issue by F4r3in** [HarlyquinForest/our-time-is-now#3]
سلام، من خودم سرور خریدم ولی فقط با همراه اول میتونم به صورت ssh بهش وصل بدم (با netmod و http custom) و وقتی با وای فای یا ایرانسل امتحان می کنم وصل نمیشه.
میتونین منو راهنمایی کنین که مشکل کجاست؟
جالب اینجاست که با یکی از سرورهایی که شما گذاشته بودین (vpnjantit) تونستم با وای فای وصل بشم.
وقتی هم که از طریق cmd ویندوز میخوام به صورت ssh متصل بشم ارور زیر رو میگیرم:
ssh_dispatch_run_fatal: Connection to ip port 22: Connection timed out

**Comment by HarlyquinForest** [comment]
سلام 
پورت پیش فرض ssh رو ۲۲ ست شده. بهتره این مورد رو تغییر بدید. یک ویدیو در مورد کانفیگ ssh درست کردم اگر اون رو ندید یه نگا بندازید می تونید کانکشن بهتری داشته باشید با کانفیگ بهتر. اول بررسی کنید که علت عدم اتصال به دلیل پورت هست یا خیر که معمولا همینه. 
https://youtu.be/7HnudWvVuzA
جالبه معمولا همه به همراه اول مشکل دارن مورد شما برعکسه ! :)

**Comment by F4r3in** [comment]
> سلام پورت پیش فرض ssh رو ۲۲ ست شده. بهتره این مورد رو تغییر بدید. یک ویدیو در مورد کانفیگ ssh درست کردم اگر اون رو ندید یه نگا بندازید می تونید کانکشن بهتری داشته باشید با کانفیگ بهتر. اول بررسی کنید که علت عدم اتصال به دلیل پورت هست یا خیر که معمولا همینه. https://youtu.be/7HnudWvVuzA جالبه معمولا همه با همراه اول مشکل دارن مورد شما برعکسه ! :)

مجددا سلام، من ویدیو تون رو نگاه کردم ولی متاسفانه من اطلاعاتی از شبکه و لینوکس ندارم و راه اندازی vpn روی سرور رو هم از ویدیوهای یوتیوب یاد گرفتم.
یه سوال: اگر من طبق ابتدای ویدیو تون یه پورت دیگه علاوه بر پورت 22 اضافه کنم و یوزری هم نسازم (با همون root لاگین کنم) آیا مشکلم حل میشه؟

یه سوال دیگه: من با وای فای سعی کردم از طریق ssh به دو تا سرور مختلف (یکی سرور خودم و اون یکی سرور vpnjantit) با پورت 22 متصل بشم. که فقط تونستم به سرور vpnjantit وصل بشم. الان سوال اینجاست که اگه isp من پورت 22 رو بسته پس چرا تونستم به سرور دوم متصل شم و اگر نبسته پس چرا نمیتونم به سرور خودم وصل شم؟

در مورد حرف آخرتون هم، طبق اطلاعاتی که از دوستام گرفتم همراه اول در تهران به شدت فیلتر شده و ایرانسل در شهرستان ها. من خودم چون تو شهرستانم می تونم با همراه اول وصل بشم. البته فقط ssh سرعت قابل قبولی داره

ببخشید طولانی شد.

**Comment by HarlyquinForest** [comment]
@F4r3in 

پورت ۲۲ کلا بسته نشده فقط برای تعدادی از رنج آی پی ها و دیتاسنترهای خارج رو فیلتر کردن.‌
احتمال اینکه با پورت عوض کردن مشکلتون حل بشه زیاده. 

جالبه من هم شهرستانم ولی با همراه اول بیشتر مشکل داریم تا ایرانسل.‌

بازم مشکلی بود درخدمتم.

**Comment by F4r3in** [comment]
@HarlyquinForest 
سلام من پورت ssh رو عوض کردم و مشکلم حل شد. الان روی تمام نت ها (وای فای، همراه اول و ایرانسل) وصل هستم و سرعت عالیه.
با اجازه ادمین من دستورات سرور رو اینجا مینویسم برای کسایی که مثل من اطلاعات برنامه نویسی ندارن.
1. به سرور تون کانکت شین و با دستور زیر چک کنین که پورت ssh تون چه پورتی هست (اکثرا باید 22 باشه)
`sudo ss -tupln`
2. دستور زیر رو وارد کنین تا پورت رو تغییر بدین.
`sudo vim /etc/ssh/sshd_config`
اگر ازتون سوالی پرسید، E رو به معنای edit بزنین تا وارد کانفیگ بشه.
3. وقتی وارد کانفیگ شدین دنبال عبارت زیر بگردین:
`#Port 22`
4. کلید I کیبورد رو بزنین که بتونین ادیت کنین.
5. عبارت مرحله 3 رو به عبارت زیر تغییر بدین و به جای x پورت دلخواه خودتون رو بذارین.
```
Port 22
Port x
```
6. کلید esc در کیبورد رو بزنین و بعد عبارت زیر رو تایپ کرده و اینتر بزنین.
`:x`
7. با دستور زیر sshd رو ری استارت کنین.
`sudo systemctl restart sshd`
8. با دستور زیر مجددا چک کنین که پورت جدید اضافه شده باشه.
`sudo ss -tupln`
9. تمام. به سرور تون با پورت جدید متصل بشین.

لازمه که بگم من این اطلاعات رو از ویدیویی که ادمین تو یوتیوب گذاشته بود استخراج کردم و اگه میخواین حرفه ای تر کار کنین اون ویدیو رو ببینین.
[](https://youtu.be/7HnudWvVuzA)

با تشکر از ادمین و تمام برنامه نویس ها که این روز ها دسترسی ما به اینترنت رو ممکن می کنن.

**Comment by HarlyquinForest** [comment]
@F4r3in 
فوق العادید. ممنون بخاطر توضیحات 
پین کردم این issue که بقیه بهتر ببیننش.
