### ISSUE TITLE
ارور Sniffer detected()

### ISSUE THREAD

**Issue by shahriarTaheriDev** [HarlyquinForest/our-time-is-now#4]
سلام و خسته نباشین 
من با نت دیتا (رایتل) از گوشی هات اسپات میکنم و از برنامه netmod استفاده میکنم و چند روزه به این اررور تو لاگ میخورم .
[23:04:05] SSH service stopped
[23:04:05] Proxy service stopped
[23:04:05] Sniffer tool detected(), please close the app before continue

**Comment by HarlyquinForest** [comment]
سلام 

ببخشید که کمی دیر جواب میدم. 
کدوم ورژن netmod استفاده می کنید؟ تنظیمات خاصی روی شبکه تون اعمال کردید ؟

**Comment by shahriarTaheriDev** [comment]
مشکلی  نیست 
مثل اینکه از طرف سرویس دهنده بود این مشکل ...
ممنون
